# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

cros_pre_src_prepare_patches() {
  eapply "${CROS_FILES_DIR}"/"${P}"-handle-memory-leak-error.patch || die
}
