# Copyright 2011 The ChromiumOS Authors
# Distributed under the terms of the GNU General Public License v2

cros_post_src_install_install_mask() {
	# chromeos-base/chromeos-auth-config installs these files.
	rm -v "${ED}"/etc/pam.d/sudo{,-i} || die

	# We don't need to init these dirs.
	rm -v "${ED}"/usr/lib/tmpfiles.d/sudo.conf || die
}
