# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

cros_pre_src_configure_clang() {
	# gcc provides $CHOST-cpp, we want to use clang instead.
	export CPP=clang-cpp
}
