# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

cros_pre_src_prepare_patches() {
	eapply "${CROS_FILES_DIR}/cherry/b4ac7d9af7cb5edfcfcbda035ed8b8c218ba8564.patch"
}
