# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

cros_pre_src_prepare_patches() {
	eapply "${CROS_FILES_DIR}"/"${P}"-fix-hole-detection-raw.patch
}
